services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile.prod
      args:
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_API_KEY=${VITE_SUPABASE_API_KEY}
        - VITE_API_URL=${VITE_API_URL}
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=production
    env_file:
      - ./.env
    command: npm start
